packages:
  - "packages/*"
allowBuilds:
  '"': true
  '[': true
  ']': true
  b: true
  d: true
  e: true
  esbuild: true
  i: true
  l: true
  s: true
  simple-git-hooks: true
  u: true
approveBuildsFor: simple-git-hooks
approveBuildsOnInstall: true
